# Generated by Django 2.0.4 on 2018-04-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_nominee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy_holder',
            name='term',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
